//! Compile-time build information for shiotsuchi-core.

// Include the file generated by core/build.rs.
include!(concat!(env!("OUT_DIR"), "/embedded_model.rs"));

// Suppress dead_code lint on EMBEDDED_PREDICTOR_BYTES (used in tokenizer.rs's own include!).
const _: () = {
    let _ = EMBEDDED_PREDICTOR_BYTES;
};

/// Whether a Vaporetto model was embedded at build time.
pub const HAS_MODEL_EMBEDDED: bool = !EMBEDDED_PREDICTOR_HASH.is_empty();

/// The SHA-256 hash of the embedded Vaporetto predictor, or empty string if none embedded.
pub const EMBEDDED_MODEL_HASH: &str = EMBEDDED_PREDICTOR_HASH;

// ── Build features (core crate) ───────────────────────────────────────────────

pub const FEATURE_WATCHER: bool = cfg!(feature = "watcher");
pub const FEATURE_ASYNC_INDEX: bool = cfg!(feature = "async-index");

// ── Transitive dependency features ───────────────────────────────────────────
// cfg!(feature = "...") only resolves features declared in THIS crate.
// These constants reflect the actual dependency configuration in core/Cargo.toml.

/// ort crate is built with `download-binaries` feature.
pub const DEP_ORT_DOWNLOAD_BINARIES: bool = true;
/// vaporetto is built with `charwise-pma` feature.
pub const DEP_VAPORETTO_CHARWISE_PMA: bool = true;
/// vaporetto is built with `tag-prediction` feature.
pub const DEP_VAPORETTO_TAG_PREDICTION: bool = true;
/// vaporetto is built with `cache-type-score` feature.
pub const DEP_VAPORETTO_CACHE_TYPE_SCORE: bool = true;
/// vaporetto is built with `fix-weight-length` feature.
pub const DEP_VAPORETTO_FIX_WEIGHT_LENGTH: bool = true;
/// rusqlite is built with `bundled` feature.
pub const DEP_RUSQLITE_BUNDLED: bool = true;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn has_model_embedded_matches_hash_emptiness() {
        assert_eq!(HAS_MODEL_EMBEDDED, !EMBEDDED_PREDICTOR_HASH.is_empty());
    }

    #[test]
    fn embedded_predictor_hash_accessible() {
        let _: &str = EMBEDDED_PREDICTOR_HASH;
    }

    #[test]
    fn dependency_features_use_core_constants() {
        // Inside a `const {}` block, the assert is evaluated at compile time so
        // a value flip to `false` is caught immediately during compilation,
        // not at test runtime.  Clippy's `const_evaluatable_checked` lint
        // covers this exact pattern.
        const _: () = const { assert!(DEP_VAPORETTO_CHARWISE_PMA) };
    }
}
